name: 'Urban_Mobility_Demo_Luminates_2025'
config-version: 2
version: '1.0.0'

profile: 'urban_mobility_demo'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Urban_Mobility_Demo_Luminates_2025:
    +materialized: view
    +schema: dbt_dev